version: '3.5'

services:
  hostapd:
    container_name: hostapd_container
    image: simonchuang12/rpi-hostapd
    network_mode: "host"
    privileged: true 
    restart: on-failure
    volumes:
       - ./hostapd/hostapd.conf:/etc/hostapd/hostapd.conf
  squid-alpine-ssl:  
      container_name: squid_container
      image: alatas/squid-alpine-ssl:r3
      environment:
        - CN=calado.local
        - O=calado
        - OU=calado
        - C=BR
      ports:
        - "3128:3128"
        - "4128:4128"
      volumes:
        - ./squid/log:/var/log/
        - ./squid/conf/squid.conf:/etc/squid/squid.conf
        - ./squid/cache:/var/cache
        - ./squid/cert:/etc/squid-cert
      restart: always
